@startuml
skinparam classAttributeIconSize 0

class Государство {
  -словарь_органов
  +добавить_орган(название: str, орган: obj): None
  +убрать_орган(название: str): None
}

class Правительство {
  #премьер_министр
  #зам_премьер_министра
  #министры
  +рассмотреть_законопроект(номер: int): bool
  +инициировать_законопроект(номер: int, название: str): None
  +изменение_мин_зарплаты(новое_значение: float): str
}

class Парламент {
  +дача_согласия_на_назначение_премьера(имя: str): bool
  +инициировать_законопроект(номер: int, название: str): None
  +рассмотреть_законопроект(номер: int): bool
  +одобрить_бюджет(величина: float): bool 
}
' #инфраструктура 

class Президент {
  -имя
  -возраст
  +назначить_премьера(имя: str): str
  +утверждение_гос_бюджета(новое_значение: float): str   
  +утвердить_законопроект(номер: int): str
  +инициировать_законопроект(номер: int, название: str): None
}
' республиканский бюджет

class Законопроект {
  -название
  -номер
  -описание
  +в_процессе_рассмотрения
} 

class Закон {
  -активный
  +активировать_закон(номер: int): str
}

class Население {
  -общее_население
  -процент_нетрудоспособных
  +средняя_зп
  +оплата_налогов(процент: float): float
  +инициировать_законопроект(номер: int) -> str
}

class Инфраструктура{
  -общаяя_протяженность_дорог
  -колво_соц_зданий
  -эл_и_вод_снабжение
  -обновление(бюджет: float): str
}

class Экономика{
  -состояние
  -уровень_инфляции
  -гос_бюджет
  -подоходный_налог
  +налогооблажение(процент: float): float
  +выделить_бюджет(): float
  +добавить_в_бюджет(сумма: float): str
  +отнять_из_бюджета(сумма: float): str
}

class Конституция{
  -колво_законов
  -разделы
  -дата_принятия
  -высшая_юр_сила
  +добавить_закон(номер: int): str
  +убрать_закон(номер: int): str
}

interface Инициатор_законопроекта {
  инициировать_законопроект()
}
interface Ревьюер_законопроекта {
  рассмотреть_законопроект()
}

abstract class Правовой_акт{

}


Государство "1" *-- "1" Правительство
Государство "1" *-- "1" Парламент
Государство "1" *-- "1" Президент
Государство "1" *-- "1" Конституция
Государство "1" *-- "1" Экономика
Государство "1" *-- "1" Инфраструктура
Государство "1" *-- "1" Население
Конституция "1" o-- "1..*" Закон

' Закон "1" --|> "1" Законопроект: наследует

Закон ..|> Правовой_акт
Законопроект ..|> Правовой_акт

Президент ..|> Инициатор_законопроекта
Население ..|> Инициатор_законопроекта
Парламент ..|> Инициатор_законопроекта
Правительство ..|> Инициатор_законопроекта

Президент ..|> Ревьюер_законопроекта
Парламент ..|> Ревьюер_законопроекта
Правительство ..|> Ревьюер_законопроекта

' ClassName1 o-- ClassName2
' ClassName1 *-- ClassName2
' ClassName3 --|> ClassName4: наследует



@enduml
