@startuml
skinparam classAttributeIconSize 0

class Государство {
  -президент
  -правительство
  -парламент
  -верховный_суд
  -бюджет
  -внешние_отношения
}

class Правительство {
  #премьер_министр
  #зам_премьер_министра
  #министры
  -одобрить_бюджет(): True
  -рассмотреть_законопроект()
  
}

class Парламент {
  -количество_людей
  -утверждение_бюджета()   
  -дача_согласия_на_назначение()
  -рассмотреть_законопроект()
}

class Президент {
  -имя
  -возраст
  -назначить_премьера(имя: str): None
  -утвердить_законопроект()
}

class Законопроект {
  -название
  -описание
  +в_процессе_рассмотрения
} 

class Закон {
  -название
  -активный
  активировать_закон()
}

class Граждане {
  +общее_население
  +средняя_зп
}

class Инфраструктура{
  -общаяя_протяженность_дорог
  -колво_соц_зданий
  -уровень_интернета
  -обновление()
}

class Экономика{
  -состояние
  -уровень_инфляции
  -гос_бюджет
  -подоходный_налог
  -налогооблажение()
  -добавить_в_бюджет()
  -отнять_из_бюджета()
  -выделить_бюджет()
}

class Конституция{
  -колво_законов
  -закон
  -разделы
  -дата_принятия
  -высшая_юр_сила
  -добавить_закон()
}

Государство "1" *-- "1" Правительство
Государство "1" *-- "1" Парламент
Государство "1" *-- "1" Президент
Государство "1" *-- "1" Конституция
Государство "1" *-- "1" Экономика
Государство "1" *-- "1" Инфраструктура
Конституция "1" *-- "1..*" Закон

' ClassName1 o-- ClassName2
' ClassName1 *-- ClassName2
' ClassName3 --|> ClassName4: наследует



@enduml
