@startuml 
' title Диаграмма состояния законопроекта в РБ
hide empty description

[*] --> Сформирован
Сформирован-->ОжиданиеРешенияПП: внесение

ОжиданиеРешенияПП --> Отклонен: [отклонен]
ОжиданиеРешенияПП --> ОдобренПП: [одобрен]
ОдобренПП --> ОжиданиеРешенияСР

ОжиданиеРешенияСР --> Отклонен: [отклонен]
ОжиданиеРешенияСР --> ОдобренСР: [одобрен]


ОдобренСР --> ОжиданиеРешенияПР
ОжиданиеРешенияПР --> Отклонен
ОжиданиеРешенияПР --> ПринятПР



Отклонен --> [*]
ПринятПР --> [*]

@enduml